services:
  - type: web
    name: financeiro-familiar-app
    runtime: python
    buildCommand: cd finance_app && pip install -r requirements.txt
    startCommand: cd finance_app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_DB_PATH
        value: /var/data/finance.db
    disk:
      name: financeiro-data
      mountPath: /var/data
      sizeGB: 1
